Feature/constrain parent pages
Q42/sanity-plugin-page-tree pull request #21
Opened 2024-02-23 11:59 UTC by ThomasBroch

This PR expands the tree config with an option to define, for each document type, which types of documents they can have as parents. 

This feature has been implemented in three areas:
- The generation of the parent field defenition. There, the references to also take this (optional) setting into account.
- The new-page + button menu in the page tree layout.
- If the above two fail, there is also a validator that fetches the type of the selected parent document and validates it against the allowed parent types, of those are available.

2024-03-14 21:57 UTC, tim-vyg commented
Love this feature!

2024-04-08 09:46 UTC, tstikvoort requested changes
Great! There a couple of typo's.

The only thing I am missing is an empty state, when non of the pages has marked a certain page type as allowedParents.

2024-04-08 09:46 UTC, tstikvoort commented on README.md
> +  pageSchemaTypes: ['homePage', 'contentPage', 'contentChildPate'],
```suggestion
  pageSchemaTypes: ['homePage', 'contentPage', 'contentChildPage'],
```

2024-04-08 09:46 UTC, tstikvoort commented on README.md
> +  alllowedParents: {
```suggestion
  allowedParents: {
```

2024-04-08 09:46 UTC, tstikvoort commented on src/validators/parent-validator.ts
> +    const alllowedParents = config.alllowedParents?.[ownType];
```suggestion
    const allowedParents = config.allowedParents?.[ownType];
```

2024-04-08 09:46 UTC, tstikvoort commented on src/validators/parent-validator.ts
> +    if (alllowedParents === undefined) {
```suggestion
    if (allowedParents === undefined) {
```

2024-04-08 09:46 UTC, tstikvoort commented on src/validators/parent-validator.ts
> +    if (!alllowedParents.includes(selectedParentType)) {
```suggestion
    if (!allowedParents.includes(selectedParentType)) {
```

2024-04-08 09:46 UTC, tstikvoort commented on src/types.ts
> +  alllowedParents?: Record<string, string[]>;
```suggestion
  allowedParents?: Record<string, string[]>;
```

2024-04-09 08:01 UTC, ThomasBroch commented
@tstikvoort Good catch! In the empty state, it now disables the button and shows this tooltip:
<img width="421" alt="Screenshot 2024-04-09 at 09 58 25" src="https://github.com/Q42/sanity-plugin-page-tree/assets/37216178/3b3edb75-8b54-458c-b38f-37d010df6dd4">

2024-04-10 13:43 UTC, djohalo2 commented on src/components/PageTreeViewItemActions.tsx
> +        The allowed parents configuration prevents this document type from being a parent to any other document.
I think this text is just a little bit too technical for the average content editor. How about `This page cannot contain any child pages.` or something similar?

2024-04-10 14:19 UTC, djohalo2 approved these changes

2024-04-10 14:19 UTC, merged